kind: pipeline
type: docker
name: Default

steps:
  - name: rsync
    image: drillster/drone-rsync
    environment:
      rsync_key:
        from_secret: pkey
    settings:
      user: root
      hosts:
        - ss.think2011.net
      source: ./fff.txt
      target: ~/tmp/
    secrets: [rsync_key]
