kind: pipeline
type: docker
name: Default

steps:
  - name: rsync
    image: drillster/drone-rsync
    commands:
      - ls
    settings:
      user: root
      hosts:
        - ss.think2011.net
      source: ./fff
      target: ~/tmp/
