name: test

on:
  push:
    branches:
      - master

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn
      - run: ls

  # deploy-cron-task1:
  #   runs-on: ubuntu-latest
  #   needs: check-and-build
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./.github/actions/docker-build-and-publish
  #       with:
  #         project: 'cron-task1'
  #         tag: 'test'
  deploy-sku-manager:
    runs-on: ubuntu-latest
    needs: check-and-build
    steps:
      - run: ls
